### PR TITLE
Remove unused getReducer function

### PR DESCRIPTION
**Pull request by tgriesser**
Not sure if this was an artifact from a previous version, or something intended to be used but wasn't.

### CODE REVIEW

**Comment by stefanpenner** [comment]
@jlongster friendly reminder

**Comment by jlongster** [comment]
Sorry guys, working on this lib again now

**Comment by jlongster** [comment]
I get way too many github pings these days, I've got to figure out a way to manage them better

**Comment by jlongster** [comment]
Thanks!

**Pull request merged**
